<a href="https://colab.research.google.com/github/Tveralina/Artificial_Intelligence/blob/master/Adaptive_method_Tverkaeva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Сигмоида 
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [3]:
# Набор входных данных
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])

In [4]:
# Выходные данные            
y = np.array([[0,0,1,1]]).T
print(y)

[[0]
 [0]
 [1]
 [1]]


In [5]:
# Делаем случайные числа более определёнными
np.random.seed(1)

In [6]:
# Инициализируем веса случайным образом со средним 0
syn0 = 2*np.random.random((3,1)) - 1
print(syn0)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [8]:
for iter in range(1000):

    # Прямое распространение
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    
    # Насколько ошиблись?
    l1_error = y - l1

    # Перемножение с наклоном сигмоиды на основе значений в l1
    l1_delta = l1_error * nonlin(l1,True)

    # Обновление веса
    syn0 += np.dot(l0.T,l1_delta) # !!!

print ("Выходные данные после тренировки:")
print (l1)

Выходные данные после тренировки:
[[0.02210697]
 [0.01793972]
 [0.98540523]
 [0.98200075]]
